### PR TITLE
SpigotPE is being directed to a different site

### PR DESCRIPTION
**Pull request by jrodr10**

### CODE REVIEW

**Comment by AvgZing** [comment]
It's linuxlogo, don't trust him.

**Comment by AvgZing** [comment]
If any of you remember the whole drama with Tesseract, he is the cause.

**Comment by jrodr10** [comment]
@TheRoyalBlock I don't understand what my past has to do with a commit clearly stating with public self-proof... but sure don't trust me look for yourself

**Comment by Thunder33345** [comment]
the org is the same, so i would give a pass

**Pull request closed without merging**
